spring:
  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: http://localhost:9000/oauth2/introspect
          client-id: messaging-client
          client-secret: secret
server:
  port: 8082
logging:
  level:
    datasource-query-logger: INFO
    org.springframework.data: DEBUG